# Generated by Django 3.1.1 on 2021-02-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=266, null=True)),
                ('category', models.CharField(blank=True, max_length=266, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=266, null=True)),
                ('initial_price', models.FloatField(blank=True, null=True)),
                ('final_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('original_pics', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('pics1', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('pics2', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('pics3', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
            ],
        ),
    ]
