# Generated by Django 3.1.1 on 2021-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210216_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_pics',
            field=models.ImageField(blank=True, null=True, upload_to='akwaoche/static/images'),
        ),
    ]
