# Generated by Django 3.1.1 on 2021-02-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210216_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_pics',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pics1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pics2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='pics3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
