# Generated by Django 3.1.1 on 2021-02-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210216_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_pics',
            field=models.ImageField(blank=True, default=False, null=True, upload_to=''),
        ),
    ]
