# Generated by Django 3.1.1 on 2021-02-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210216_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mode',
            field=models.CharField(blank=True, default='Yard', max_length=200, null=True),
        ),
    ]
