# Generated by Django 3.1.7 on 2021-02-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_advert_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='advert4heading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='advert4pics',
            field=models.ImageField(blank=True, null=True, upload_to='slides/'),
        ),
        migrations.AddField(
            model_name='advert',
            name='advert4subheading',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='advert4writeup',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
